### ISSUE TITLE
Add support for early/late mixins

### ISSUE THREAD

**Issue by makamys** [GTNewHorizons/ExampleMod1.7.10#131]
Right now the build script doesn't have support for early/late mixins, forcing mods that use it (such as [Hodgepodge](https://github.com/GTNewHorizons/Hodgepodge/blob/5a6bd17c93cb25b6cbb0693c3775451223cdaa4c/.gitignore) and [NotFine](https://github.com/jss2a98aj/NotFine/blob/7b36c09f70fd8f13907e5e2ce1c3169a2fba4f25/.gitignore)) to use a custom gitignore with this line removed:
https://github.com/GTNewHorizons/ExampleMod1.7.10/blob/c861c6b0486ca5dfd228e2f62c76e88b0dea47b4/.gitignore#L29

**Comment by mitchej123** [comment]
This should be updated to only exclude the autogenerated mixins.blah.json; and not the (currently not autogenerated) mixin.blah.(early|late).json.  Or updated to also generate the early/late.json if they're missing.  🤔

**Comment by makamys** [comment]
Maybe the autogenerated configs could reside in a different temp directory, which would be added as an extra dir to `sourceSets.main.resources.srcDirs`. That would remove the need to gitignore anything from `src`.

**Comment by eigenraven** [comment]
RFG provides a injectedTags sourceset in the build folder for generating the class with mod version/id/etc., which could also be used for adding resources to the built jar without putting them in the main source folders
