### ISSUE TITLE
Make publishing to maven optional

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/ExampleMod1.7.10#137]
Add an option to disable maven publishing. Also make the URL configurable (with a default to GTNH)

**Comment by Kurandx** [comment]
Yes it would be nice.
It would be nice to add an authorization configuration for publishing to Maven (preferably take it from environment variables).
Currently need to edit build.gradle to achieve this...

**Comment by eigenraven** [comment]
Solved in a recent update via gradle.properties
