### ISSUE TITLE
Gradle init failure on first import, the second

### ISSUE THREAD

**Issue by MalTeeez** [GTNewHorizons/ExampleMod1.7.10#141]
Tried with Java 17, spotless.gradle is missing
Log [gist](https://gist.github.com/MalTeeez/02dd05f524a10d800f5af4b5a7a86d34)

**Comment by eigenraven** [comment]
Replace settings.gradle with settings.gradle.example

**Comment by MalTeeez** [comment]
That fixed it, thanks!
