### ISSUE TITLE
can't import project with error

### ISSUE THREAD

**Issue by DancingSnow0517** [GTNewHorizons/ExampleMod1.7.10#269]
the log show 

An exception occurred applying plugin request [id: 'com.gtnewhorizons.gtnhconvention']
> Failed to apply plugin 'com.gtnewhorizons.gtnhconvention'.
   > None of the given URL mirrors are live: https://maven2.ic2.player.to/https://maven.ic2.player.to/

**Comment by Hotten1** [comment]
2 weeks leaves this project unusable

**Comment by ChrisJStone** [comment]
This project is usable. The only time I've had a issue with not being able to get a dependency is if the package name is incorrect.
