### ISSUE TITLE
Problem with kotlin

### ISSUE THREAD

**Issue by yannickWWW** [GTNewHorizons/ExampleMod1.7.10#270]
Hey, is it possible to integrate kotlin support into the project? I've tried to do this through the 'dependencies.gradle' file using 'shadowCompile', but it's not copying it to the root and my Kotlin is also not present in the final .jar. Could someone please help me with this? Thank you.

**Comment by Glease** [comment]
the standard practice for kotlin support is to depend on forgelin, then apply kotlin plugin and set kotlin options (if any) in addon.gradle. You can refer to https://github.com/GTNewHorizons/MX-Random/ as an example.

Do note that this means the player would have to install forgelin to use your mod.

**Comment by yannickWWW** [comment]
Thanks
