### ISSUE TITLE
How to disable git check?

### ISSUE THREAD

**Issue by HenryLoenwind** [GTNewHorizons/ExampleMod1.7.10#277]
![image](https://github.com/GTNewHorizons/ExampleMod1.7.10/assets/1485873/be28fea9-f79f-401f-bc23-d82cb2156a5d)

It obviously isn't working, so how do I disable it?

**Comment by mitchej123** [comment]
Because you didn't make it a git repo.   It also literally tells you how in the error message.

**Comment by HenryLoenwind** [comment]
> Because you didn't make it a git repo. It also literally tells you how in the error message.

So why does git think it's a git repo?

**Comment by mitchej123** [comment]
Because you didn't git init, or clone, or do anything else to make it a git repo?

**Comment by HenryLoenwind** [comment]
read the screenshot and don't just assume

**Comment by mitchej123** [comment]
I did.  
![Screenshot_20240706-235852](https://github.com/GTNewHorizons/ExampleMod1.7.10/assets/1894689/fca95ecd-1802-4637-b4de-04ea953b0078)

**Comment by mitchej123** [comment]
Screenshots aren't helpful.  Full text logs of how to reproduce something is.

**Comment by mitchej123** [comment]
Also, read the error message. It literally tells you how to work around it.
