### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/ExampleMod1.7.10#281]
Build file '/home/pc/JavaProjects/ExampleMod1.7.10-master/build.gradle' line: 2

An exception occurred applying plugin request [id: 'com.gtnewhorizons.gtnhconvention']
> Failed to apply plugin 'com.gtnewhorizons.gtnhconvention'.
   > Not a git repo, and no VERSION set.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

how to fix it?

**Comment by Lyfts** [comment]
https://github.com/GTNewHorizons/ExampleMod1.7.10?tab=readme-ov-file#getting-started
