### ISSUE TITLE
Minecraft JAR Location returns 403

### ISSUE THREAD

**Issue by MalTeeez** [GTNewHorizons/ExampleMod1.7.10#87]
This seems related to https://bugs.mojang.com/browse/MCL-22665 , on :downloadClient via https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.jar I get a 403 HTTP response which means setting up new environments is currently impossible.

**Comment by glowredman** [comment]
Fixed by https://github.com/GTNewHorizons/ExampleMod1.7.10/pull/83
