### ISSUE TITLE
Relocation causes UnsatisfiedLinkError with JNA

### ISSUE THREAD

**Issue by drori200** [GTNewHorizons/ExampleMod1.7.10#96]
After shading and relocating my discord rich presence library (will be refered to as RPC from here on), trying to run the game with the mod causes a `UnsatisfiedLinkError` when my rpc library uses a JNA method.

More info on this can be found in this issue:
https://github.com/java-native-access/jna/issues/679

A fix for this (and probably other libraries that use native methods, which from what i infer is the problem here) would be implementing a way for the shadow configuration to if specific packages are to not be relocated.

A possible approach for this can be creating an array in `gradle.properties` containing package names to not relocate and then in the shadowJar tasks check if it is not empty and if the packages specified in the array are presenet while relocating. If they are, shade them to the root of the jar.

This is to not be confused with using `exclude module` when declaring the dependency which will exclude the package entirely.

**Comment by glowredman** [comment]
It is quite possible that your use-case is already covered by the shadow plugin.
UserGuide: https://imperceptiblethoughts.com/shadow/
Example: https://github.com/GTNewHorizons/GTNHMixins/blob/master/build.gradle

**Comment by drori200** [comment]
> It is quite possible that your use-case is already covered by the shadow plugin.
> UserGuide: https://imperceptiblethoughts.com/shadow/
> Example: https://github.com/GTNewHorizons/GTNHMixins/blob/master/build.gradle

Wouldn't doing something like this manually break compatibility with the updates for the buildscript?

**Comment by glowredman** [comment]
You could probably do it via the `addon.gradle` file

**Comment by drori200** [comment]
So do a second relocation of the packages after the first one is done?
